export const DELETE = 'Delete';
export const EDIT = 'Edit';
export const NEW_POST = 'New post';
export const POST_TITLE = 'Post Title';
export const POST_BODY = 'Post body';
export const DISCARD = 'Discard';
export const CREATE_POST = 'Create post';
export const EDIT_POST = 'Edit post';
export const TEXT = 'text';
export const EMPTY_STRING = '';
export const LOADER_COLOR = '#e61973';
export const MODIFY_POST = 'modify post';
export const LOGO = 'logo';
export const FILTERS = 'Filters';
export const SORT = 'Sort';
export const CHECKBOX = 'checkbox';

export const TITLE_CHAR_LIMIT = 80;
export const BODY_CHAR_LIMIT = 600;